
[bell]
animation = "EaseOutExpo"
color = "#909090"
duration = 10

[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

[colors.normal]
black   = '#090618'
red     = '#c34043'
green   = '#76946a'
yellow  = '#c0a36e'
blue    = '#7e9cd8'
magenta = '#957fb8'
cyan    = '#6a9589'
white   = '#c8c093'

[colors.bright]
black   = '#727169'
red     = '#e82424'
green   = '#98bb6c'
yellow  = '#e6c384'
blue    = '#7fb4ca'
magenta = '#938aa9'
cyan    = '#7aa89f'
white   = '#dcd7ba'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0018\u0017"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018\u0013"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018p"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018n"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018y"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018c"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018h"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018j"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018k"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0018l"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00181"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00182"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00183"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00184"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00185"
key = "Key5"
mods = "Command"

[scrolling]
history = 0

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
dynamic_title = false
padding = { x = 15, y = 0 }

[general]
live_config_reload = false
