#!/usr/bin/env bash

trap 'echo >&@ "$0:Error at $LINENO: $BASH_COMMAND"; exit 1;' ERR

f="$(greadlink -e "$1")"

osascript \
	-e 'on run args' \
	-e 'set the clipboard to POSIX file (first item of args)' \
	-e 'end' \
	"$f"

