#!/bin/bash

if [ -n "$NVIM" ] && which nvr >/dev/null 2>&1; then
	nvr --remote-tab-wait --nostart -c 'call UnmapZ()' '+set bufhidden=wipe' "$@"
elif which nvim >/dev/null 2>&1; then
	nvim "$@"
else
	"$(which -a vi | tail -n 1)" "$@"
fi
