#!/bin/bash

if [ -n "$NVIM_LISTEN_ADDRESS" ] && which nvr >/dev/null 2>&1; then
	nvr --remote-tab-wait --nostart -c 'call Unmap_Z()' '+set bufhidden=wipe' "$@"
elif which nvim >/dev/null 2>&1; then
	nvim "$@"
else
	"$(which -a vim | tail -n 1)" "$@"
fi
